In [1]:
from pathlib import Path

import pandas as pd

from IPython.display import display

pd.set_option(
    "display.max_columns",
    None
)


def find_project_root(
    start_path: Path
) -> Path:

    start_path = start_path.resolve()

    for path in [
        start_path,
        *start_path.parents
    ]:

        if (
            (path / "data").exists()
            and (path / "src").exists()
        ):
            return path

    raise FileNotFoundError(
        "Project root could not be found."
    )


PROJECT_ROOT = find_project_root(
    Path.cwd()
)

REPORT_PATH = (
    PROJECT_ROOT
    / "reports"
    / "opportunity"
)

print(PROJECT_ROOT)

C:\Users\Impana\OneDrive\Data Analyst Tutorial\Project\InsightGuard AI

In [2]:
all_opportunities = pd.read_csv(
    REPORT_PATH
    / "all_opportunities_ranked.csv"
)

display(
    all_opportunities.head(20)
)

,rank,opportunity_id,opportunity_name,opportunity_type,opportunity_score,opportunity_level,confidence_score
0,1,product_beleza_saude,beleza_saude,product,85.434149,High,99.68
1,2,seller_4a3ca9315b744ce9f8e9374361493884,4a3ca9315b744ce9f8e9374361493884,seller,76.366630,High,99.68
2,3,seller_6560211a19b47992c3666cc44a7e94c0,6560211a19b47992c3666cc44a7e94c0,seller,73.406850,Medium,99.68
3,4,seller_4869f7a5dfa277a7dca6462dcf3b52b2,4869f7a5dfa277a7dca6462dcf3b52b2,seller,71.238063,Medium,99.68
4,5,delivery_AL,AL,delivery,68.617601,Medium,99.68
5,6,seller_cc419e0650a3c5ba77189a1882b7556a,cc419e0650a3c5ba77189a1882b7556a,seller,66.752201,Medium,99.68
6,7,seller_7c67e1448b00f6e969d365cea6b010ab,7c67e1448b00f6e969d365cea6b010ab,seller,65.712504,Medium,99.68
7,8,customer_0a0a92112bd4c708ca5fde585afaa872,0a0a92112bd4c708ca5fde585afaa872,customer,65.659187,Medium,70.68
8,9,seller_da8622b14eb17ae2831f4ac5b9dab84a,da8622b14eb17ae2831f4ac5b9dab84a,seller,63.788147,Medium,99.68
9,10,seller_955fee9216a65b617aa5c0531780ce60,955fee9216a65b617aa5c0531780ce60,seller,62.090478,Medium,99.68
10,11,product_cama_mesa_banho,cama_mesa_banho,product,61.061019,Medium,99.68
11,12,seller_1f50f920176fa81dab994f9023523100,1f50f920176fa81dab994f9023523100,seller,60.507839,Medium,99.68
12,13,seller_7a67c85e85bb2ce8582c35f2203ad736,7a67c85e85bb2ce8582c35f2203ad736,seller,60.327462,Medium,99.68
13,14,delivery_MA,MA,delivery,58.953773,Medium,99.68
14,15,seller_1025f0e2d44d7041d6cf58b6550e0bfa,1025f0e2d44d7041d6cf58b6550e0bfa,seller,58.904578,Medium,99.68
15,16,seller_fa1c13f2614d7b5c4749cbc52fecda94,fa1c13f2614d7b5c4749cbc52fecda94,seller,56.976907,Medium,99.68
16,17,seller_53243585a1d6dc2643021fd1853d8905,53243585a1d6dc2643021fd1853d8905,seller,56.938651,Medium,99.68
17,18,product_moveis_decoracao,moveis_decoracao,product,53.534115,Medium,99.68
18,19,seller_3d871de0142ce09b7081e2b9d1733cb1,3d871de0142ce09b7081e2b9d1733cb1,seller,52.436097,Medium,99.68
19,20,product_relogios_presentes,relogios_presentes,product,52.256908,Medium,99.68

In [3]:
product_opportunities = pd.read_csv(
    REPORT_PATH
    / "product_opportunities.csv"
)

display(
    product_opportunities[
        [
            "product_category_name",
            "total_orders",
            "total_revenue",
            "growth_rate",
            "average_review_score",
            "opportunity_score",
            "confidence_score",
            "opportunity_level",
        ]
    ]
    .head(10)
)

,product_category_name,total_orders,total_revenue,growth_rate,average_review_score,opportunity_score,confidence_score,opportunity_level
0,beleza_saude,8836,1441248.07,77700.000000,3.0,85.434149,99.68,High
1,cama_mesa_banho,9417,1241681.72,11060.000000,3.0,61.061019,99.68,Medium
2,moveis_decoracao,6449,902511.79,34300.000000,3.0,53.534115,99.68,Medium
3,relogios_presentes,5624,1305541.61,7740.000000,3.0,52.256908,99.68,Medium
4,esporte_lazer,7720,1156656.48,2194.736842,3.0,52.131656,99.68,Medium
5,informatica_acessorios,6689,1059272.40,2033.333333,3.0,47.334815,99.68,Low
6,utilidades_domesticas,5884,778397.77,6144.444444,3.0,40.430972,99.68,Low
7,telefonia,4199,394883.32,24500.000000,3.0,33.688803,99.68,Low
8,automotivo,3897,685384.32,3100.000000,3.0,32.698073,99.68,Low
9,cool_stuff,3632,719329.95,1400.000000,3.0,32.410159,99.68,Low

In [4]:
customer_opportunities = pd.read_csv(
    REPORT_PATH
    / "customer_opportunities.csv"
)

display(
    customer_opportunities[
        [
            "total_orders",
            "total_revenue",
            "average_order_value",
            "recency_days",
            "opportunity_score",
            "confidence_score",
            "opportunity_level",
        ]
    ]
    .head(10)
)

,total_orders,total_revenue,average_order_value,recency_days,opportunity_score,confidence_score,opportunity_level
0,1,13664.08,100.000000,333,65.659187,70.68,Medium
1,1,7274.88,53.208066,45,48.002164,70.68,Low
2,15,879.27,0.359061,8,47.377130,84.68,Low
3,1,6922.21,50.625252,34,46.890172,70.68,Low
4,4,4655.88,8.454215,21,39.647240,73.68,Low
5,1,4513.32,32.983509,25,37.439668,70.68,Low
6,1,4681.78,34.217243,68,36.912050,70.68,Low
7,1,6081.54,44.468523,278,36.659651,70.68,Low
8,1,4163.51,30.421642,31,35.862338,70.68,Low
9,1,4445.50,32.486823,89,35.371259,70.68,Low

In [5]:
seller_opportunities = pd.read_csv(
    REPORT_PATH
    / "seller_opportunities.csv"
)

display(
    seller_opportunities[
        [
            "seller_id",
            "total_orders",
            "total_revenue",
            "average_review_score",
            "average_delivery_delay",
            "growth_rate",
            "opportunity_score",
            "confidence_score",
        ]
    ]
    .head(10)
)

,seller_id,total_orders,total_revenue,average_review_score,average_delivery_delay,growth_rate,opportunity_score,confidence_score
0,4a3ca9315b744ce9f8e9374361493884,1806,235539.96,3.0,-8.954641,88.461538,76.366630,99.68
1,6560211a19b47992c3666cc44a7e94c0,1854,151265.77,3.0,-11.010434,3600.000000,73.406850,99.68
2,4869f7a5dfa277a7dca6462dcf3b52b2,1132,249640.70,3.0,-10.453161,1283.333333,71.238063,99.68
3,cc419e0650a3c5ba77189a1882b7556a,1706,129957.41,3.0,-12.346171,2400.000000,66.752201,99.68
4,7c67e1448b00f6e969d365cea6b010ab,982,239536.44,3.0,-10.832570,12.500000,65.712504,99.68
5,da8622b14eb17ae2831f4ac5b9dab84a,1314,185192.32,3.0,-10.527563,93.333333,63.788147,99.68
6,955fee9216a65b617aa5c0531780ce60,1287,160602.68,3.0,-9.626675,1016.666667,62.090478,99.68
7,1f50f920176fa81dab994f9023523100,1404,142104.98,3.0,-10.125605,483.333333,60.507839,99.68
8,7a67c85e85bb2ce8582c35f2203ad736,1160,162648.38,3.0,-11.160569,800.000000,60.327462,99.68
9,1025f0e2d44d7041d6cf58b6550e0bfa,915,172860.69,3.0,-10.388772,1187.500000,58.904578,99.68

In [6]:
delivery_opportunities = pd.read_csv(
    REPORT_PATH
    / "delivery_opportunities.csv"
)

display(
    delivery_opportunities[
        [
            "customer_state",
            "total_orders",
            "delay_rate",
            "average_delay_days",
            "average_review_score",
            "opportunity_score",
            "confidence_score",
        ]
    ]
    .head(10)
)

,customer_state,total_orders,delay_rate,average_delay_days,average_review_score,opportunity_score,confidence_score
0,AL,397,100.000000,-8.032059,3.852792,68.617601,99.68
1,MA,717,79.741379,-8.887844,3.833567,58.953773,99.68
2,SE,335,58.640943,-9.328641,3.907186,49.189015,99.68
3,CE,1279,59.118840,-10.110007,3.941870,48.120986,99.68
4,SP,40501,14.314457,-10.380350,4.246551,48.112115,99.68
5,RJ,12350,50.326002,-11.054735,3.965141,48.045764,99.68
6,PI,476,62.168486,-10.629538,3.993631,47.710308,99.68
7,BA,3256,52.995712,-10.099073,3.930009,46.707272,99.68
8,ES,1995,44.420168,-9.797109,4.079736,42.831286,99.68
9,MS,701,41.210225,-10.355558,4.160229,39.507092,99.68